module.exports = {
    "STATE-LIST": "CONNECT-MASTER-LOCATION-STATE-LIST-", // ADD COUNTRY ID
    "CITY-LIST": "CONNECT-MASTER-LOCATION-CITY-LIST-", // ADD STATE ID
    "ALL-CITY-LIST": "CONNECT-MASTER-ALL-CITY-LIST",
    "COUNTRY-LIST": "CONNECT-MASTER-LOCATION-COUNTRY-LIST",
    "1-DAY": 24 * 60 * 60,
    "7-DAYS": 24 * 60 * 60 * 7,
    CONSTANTS: "CONNECT-MASTER-CONSTANTS",
    "ALL-CITIES":"CONNECT-ALL-CITIES-LIST",
    "STATE-LIST-SERVICE-CENTER":"CONNECT-MASTER-SERVICE-CENTER-STATE-LIST",
    "CITY-LIST-SERVICE-CENTER":"CONNECT-MASTER-SERVICE-CENTER-CITY-LIST"

};
